google_key = "AIzaSyA9dfPfqOuaxUedV_1Ubp75ypyFr9a3zQ0"
google_maps_url = "https://maps.googleapis.com/maps/api/staticmap"
imagery_file = "satelite_image.png"
plume_file = "plume.png"
overlay_file = "overlay.png"