googleKey = 'AIzaSyA9dfPfqOuaxUedV_1Ubp75ypyFr9a3zQ0'
googleMapsURL = 'https://maps.googleapis.com/maps/api/staticmap'
imageryFile = 'satelite_image.png'
plumeFile = 'plume.png'
overlayFile = 'c.overlayFile'